# FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.11
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.3
RUN bin/elasticsearch-plugin remove x-pack --purge

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
